
const images={
   
    Minus: require("./images/Minus.png"),
    Plus: require("./images/Plus.png"),
    cellphone: require("./images/cellphone.png"),
    chair: require("./images/chair.png"),
    chair_icon: require("./images/chair_icon.png"),
    chairsicon: require("./images/chairsicon.png"),
    checked_icon: require("./images/checked_icon.png"),
    chkn: require("./images/chkn.png"),
    chky: require("./images/chky.png"),
    cpassword_icon: require("./images/cpassword_icon.png"),
    cupboard: require("./images/cupboard.png"),
    cupboard_icon: require("./images/cupboard_icon.png"),
    cupboardicon: require("./images/cupboardicon.png"),
    delete: require("./images/delete.png"),
    dob_icon: require("./images/dob_icon.png"),
    email_icon: require("./images/email_icon.png"),
    logout_icon: require("./images/logout_icon.png"),
    menu_icon: require("./images/menu_icon.png"),
    myorders_icon: require("./images/myorders_icon.png"),
    password_icon: require("./images/password_icon.png"),
    remove_button: require("./images/remove_button.png"),
    search_icon: require("./images/search_icon.png"),
    select_button: require("./images/select_button.png"),
    share: require("./images/share.png"),
    shopping_cart: require("./images/shopping_cart.png"),
    sofa: require("./images/sofa.png"),
    sofa_icon: require("./images/sofa_icon.png"),
    sofaicon: require("./images/sofaicon.png"),
    star_check: require("./images/star_check.png"),
    star_unchek: require("./images/star_unchek.png"),
    storelocator: require("./images/storelocator.png"),
    storelocator_icon: require("./images/storelocator_icon.png"),
    table: require("./images/table.png"),
    tableicon: require("./images/tableicon.png"),
    tables_icon: require("./images/tables_icon.png"),
    uncheck_icon: require("./images/uncheck_icon.png"),
    user_male: require("./images/user_male.png"),
    username_icon: require("./images/username_icon.png"),
    slider_img1: require("./images/slider_img1.jpg"),
    slider_img2: require("./images/slider_img2.jpg"),
    slider_img3: require("./images/slider_img3.jpg"),
    slider_img4: require("./images/slider_img4.jpg"),
    header_shopping_cart:require("./images/header_shopping_cart.png")
}

export default images